#!/bin/bash

tmux new-session -d -s immutant './scripts/cluster1'
tmux rename-window 'immutant'
tmux select-window -t immutant:0
tmux split-window -h 'sleep 30; ./scripts/cluster2'
tmux split-window -v -t 0 'sleep 30; ./scripts/cluster3'
tmux split-window -v -t 1 'sleep 30; ./scripts/cluster4'
tmux -2 attach-session -t immutant
